# Generated by Django 5.1.2 on 2024-10-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MentalHealthDirary",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="description"),
                ),
                (
                    "start",
                    models.CharField(max_length=50, verbose_name="start event date"),
                ),
            ],
            options={
                "db_table": "MetalHealthDirary",
            },
        ),
    ]
