# Generated by Django 5.1.2 on 2024-10-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SleepDiary",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                (
                    "start",
                    models.CharField(max_length=50, verbose_name="start event date"),
                ),
                ("end", models.CharField(max_length=50, verbose_name="end event date")),
            ],
            options={
                "db_table": "SleepDiary",
            },
        ),
    ]
