# Generated by Django 5.1.2 on 2024-10-12 02:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sleepCheckDiary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sleepdiary",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
